### PR TITLE
Add btcc trades river

### PR DESCRIPTION
**Pull request by Lupino**

### CODE REVIEW

**Comment by rhyolight** [comment]
Awesome! I will test this out later today.

**Comment by rhyolight** [comment]
I keep seeing the following error when I start this river and it makes its first request for data:

```
{ [Error: getaddrinfo ENOTFOUND data.btcchina.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'data.btcchina.com' }
```

I believe this is a DNS issue. Does this happen for you at all? Funny thing is that the URL works when I ping it with my browser. 

Also, please merge in master because there was one change I needed to merge to ensure the data fetching is turned on when the server starts.

**Comment by Lupino** [comment]
I rebase master and merge to my master.  will I create a new pull request on the master?

**Comment by rhyolight** [comment]
@Lupino Sorry it took so long to respond. I am just catching up on emails after HTM Challenge. 

You should be able to sync this PR with master by running:

`git checkout btcc-trades`
`git pull upstream master` (where upstream points to this remote location)
`git push origin btcc-trades` (assuming origin points to your fork remote location)

**Comment by rhyolight** [comment]
Working now!

**Comment by rhyolight** [comment]
@Lupino Woohoo! http://data.numenta.org/btcc-trades/btcc-trades/data.html Thanks a lot!

**Pull request merged**
