### PR TITLE
Addresses #42. Renders a default error template if no template name c…

### PR DESCRIPTION
**Pull request by jefffohl**
…an be found.

### CODE REVIEW

**Comment by jefffohl** [comment]
Just realized that I should probably write a test to go along with this...

**Comment by rhyolight** [comment]
@jefffohl Failure seems to have been a temporary coveralls issue. I restarted it.

**Comment by jefffohl** [comment]
@rhyolight I added a test. Let me know what you think.

**Comment by rhyolight** [comment]
:+1: awesome thanks

**Pull request merged**
